functionality:
  name: example_python
  description: A minimal example component.
  arguments:
    - type: file
      name: --input
      example: data.csv
      required: true
    - type: file
      name: --output
      direction: output
      example: filtered_output.csv
      required: true
  resources:
    - type: python_script
      path: filter_projects.py
platforms:
  - type: docker
    build:
      dockerfile: Dockerfile
  - type: native
  - type: nextflow